id: I1C930133
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:06:14+00:00'
last_modified: '2022-06-07T15:25:21.327054+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25734
  title: གཅིག་དགུ་གྱ་བཞི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '6533':
      image_group_id: I1KG25736
      title: ''
      total_pages: 645
      order: 1
      base_file: 6533.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
