id: P002890
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:26:39.418513
source_metadata:
  id: bdr:W1KG25734
  title: གཅིག་དགུ་གྱ་བཞི།
  author: ''
  volumes:
    319bd76d169e4aeebab3e466f8ea948b:
      image_group_id: I1KG25736
      title: ''
      volume_number: 1
      total_pages: 645
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
